// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.rooinaction.coursemanager.db.RegistrationRepository;
import org.rooinaction.coursemanager.model.CourseDataOnDemand;
import org.rooinaction.coursemanager.model.Registration;
import org.rooinaction.coursemanager.model.RegistrationDataOnDemand;
import org.rooinaction.coursemanager.model.StudentDataOnDemand;
import org.rooinaction.coursemanager.service.RegistrationService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RegistrationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RegistrationDataOnDemand: @Component;
    
    private Random RegistrationDataOnDemand.rnd = new SecureRandom();
    
    private List<Registration> RegistrationDataOnDemand.data;
    
    @Autowired
    CourseDataOnDemand RegistrationDataOnDemand.courseDataOnDemand;
    
    @Autowired
    StudentDataOnDemand RegistrationDataOnDemand.studentDataOnDemand;
    
    @Autowired
    RegistrationService RegistrationDataOnDemand.registrationService;
    
    @Autowired
    RegistrationRepository RegistrationDataOnDemand.registrationRepository;
    
    public Registration RegistrationDataOnDemand.getNewTransientRegistration(int index) {
        Registration obj = new Registration();
        setAttended(obj, index);
        setPaymentMade(obj, index);
        return obj;
    }
    
    public void RegistrationDataOnDemand.setAttended(Registration obj, int index) {
        Boolean attended = Boolean.TRUE;
        obj.setAttended(attended);
    }
    
    public void RegistrationDataOnDemand.setPaymentMade(Registration obj, int index) {
        Boolean paymentMade = Boolean.TRUE;
        obj.setPaymentMade(paymentMade);
    }
    
    public Registration RegistrationDataOnDemand.getSpecificRegistration(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Registration obj = data.get(index);
        Long id = obj.getId();
        return registrationService.findRegistration(id);
    }
    
    public Registration RegistrationDataOnDemand.getRandomRegistration() {
        init();
        Registration obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return registrationService.findRegistration(id);
    }
    
    public boolean RegistrationDataOnDemand.modifyRegistration(Registration obj) {
        return false;
    }
    
    public void RegistrationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = registrationService.findRegistrationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Registration' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Registration>();
        for (int i = 0; i < 10; i++) {
            Registration obj = getNewTransientRegistration(i);
            try {
                registrationService.saveRegistration(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            registrationRepository.flush();
            data.add(obj);
        }
    }
    
}
