// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.rooinaction.coursemanager.db.RegistrationRepository;
import org.rooinaction.coursemanager.model.RegistrationDataOnDemand;
import org.rooinaction.coursemanager.model.RegistrationIntegrationTest;
import org.rooinaction.coursemanager.service.RegistrationService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RegistrationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RegistrationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RegistrationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RegistrationIntegrationTest: @Transactional;
    
    @Autowired
    RegistrationDataOnDemand RegistrationIntegrationTest.dod;
    
    @Autowired
    RegistrationService RegistrationIntegrationTest.registrationService;
    
    @Autowired
    RegistrationRepository RegistrationIntegrationTest.registrationRepository;
    
    @Test
    public void RegistrationIntegrationTest.testCountAllRegistrations() {
        Assert.assertNotNull("Data on demand for 'Registration' failed to initialize correctly", dod.getRandomRegistration());
        long count = registrationService.countAllRegistrations();
        Assert.assertTrue("Counter for 'Registration' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RegistrationIntegrationTest.testFindRegistration() {
        Registration obj = dod.getRandomRegistration();
        Assert.assertNotNull("Data on demand for 'Registration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Registration' failed to provide an identifier", id);
        obj = registrationService.findRegistration(id);
        Assert.assertNotNull("Find method for 'Registration' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Registration' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RegistrationIntegrationTest.testFindAllRegistrations() {
        Assert.assertNotNull("Data on demand for 'Registration' failed to initialize correctly", dod.getRandomRegistration());
        long count = registrationService.countAllRegistrations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Registration', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Registration> result = registrationService.findAllRegistrations();
        Assert.assertNotNull("Find all method for 'Registration' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Registration' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RegistrationIntegrationTest.testFindRegistrationEntries() {
        Assert.assertNotNull("Data on demand for 'Registration' failed to initialize correctly", dod.getRandomRegistration());
        long count = registrationService.countAllRegistrations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Registration> result = registrationService.findRegistrationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Registration' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Registration' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RegistrationIntegrationTest.testFlush() {
        Registration obj = dod.getRandomRegistration();
        Assert.assertNotNull("Data on demand for 'Registration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Registration' failed to provide an identifier", id);
        obj = registrationService.findRegistration(id);
        Assert.assertNotNull("Find method for 'Registration' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRegistration(obj);
        Integer currentVersion = obj.getVersion();
        registrationRepository.flush();
        Assert.assertTrue("Version for 'Registration' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RegistrationIntegrationTest.testUpdateRegistrationUpdate() {
        Registration obj = dod.getRandomRegistration();
        Assert.assertNotNull("Data on demand for 'Registration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Registration' failed to provide an identifier", id);
        obj = registrationService.findRegistration(id);
        boolean modified =  dod.modifyRegistration(obj);
        Integer currentVersion = obj.getVersion();
        Registration merged = registrationService.updateRegistration(obj);
        registrationRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Registration' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RegistrationIntegrationTest.testSaveRegistration() {
        Assert.assertNotNull("Data on demand for 'Registration' failed to initialize correctly", dod.getRandomRegistration());
        Registration obj = dod.getNewTransientRegistration(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Registration' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Registration' identifier to be null", obj.getId());
        try {
            registrationService.saveRegistration(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        registrationRepository.flush();
        Assert.assertNotNull("Expected 'Registration' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RegistrationIntegrationTest.testDeleteRegistration() {
        Registration obj = dod.getRandomRegistration();
        Assert.assertNotNull("Data on demand for 'Registration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Registration' failed to provide an identifier", id);
        obj = registrationService.findRegistration(id);
        registrationService.deleteRegistration(obj);
        registrationRepository.flush();
        Assert.assertNull("Failed to remove 'Registration' with identifier '" + id + "'", registrationService.findRegistration(id));
    }
    
}
