// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.rooinaction.coursemanager.db.TagRepository;
import org.rooinaction.coursemanager.model.TagDataOnDemand;
import org.rooinaction.coursemanager.model.TagIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TagIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TagIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TagIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TagIntegrationTest: @Transactional;
    
    @Autowired
    TagDataOnDemand TagIntegrationTest.dod;
    
    @Autowired
    TagRepository TagIntegrationTest.tagRepository;
    
    @Test
    public void TagIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Tag' failed to initialize correctly", dod.getRandomTag());
        long count = tagRepository.count();
        Assert.assertTrue("Counter for 'Tag' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TagIntegrationTest.testFind() {
        Tag obj = dod.getRandomTag();
        Assert.assertNotNull("Data on demand for 'Tag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tag' failed to provide an identifier", id);
        obj = tagRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Tag' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tag' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TagIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Tag' failed to initialize correctly", dod.getRandomTag());
        long count = tagRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tag', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tag> result = tagRepository.findAll();
        Assert.assertNotNull("Find all method for 'Tag' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tag' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TagIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Tag' failed to initialize correctly", dod.getRandomTag());
        long count = tagRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tag> result = tagRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Tag' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tag' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TagIntegrationTest.testFlush() {
        Tag obj = dod.getRandomTag();
        Assert.assertNotNull("Data on demand for 'Tag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tag' failed to provide an identifier", id);
        obj = tagRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Tag' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTag(obj);
        Integer currentVersion = obj.getVersion();
        tagRepository.flush();
        Assert.assertTrue("Version for 'Tag' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TagIntegrationTest.testSaveUpdate() {
        Tag obj = dod.getRandomTag();
        Assert.assertNotNull("Data on demand for 'Tag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tag' failed to provide an identifier", id);
        obj = tagRepository.findOne(id);
        boolean modified =  dod.modifyTag(obj);
        Integer currentVersion = obj.getVersion();
        Tag merged = tagRepository.save(obj);
        tagRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tag' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TagIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Tag' failed to initialize correctly", dod.getRandomTag());
        Tag obj = dod.getNewTransientTag(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tag' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tag' identifier to be null", obj.getId());
        try {
            tagRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        tagRepository.flush();
        Assert.assertNotNull("Expected 'Tag' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TagIntegrationTest.testDelete() {
        Tag obj = dod.getRandomTag();
        Assert.assertNotNull("Data on demand for 'Tag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tag' failed to provide an identifier", id);
        obj = tagRepository.findOne(id);
        tagRepository.delete(obj);
        tagRepository.flush();
        Assert.assertNull("Failed to remove 'Tag' with identifier '" + id + "'", tagRepository.findOne(id));
    }
    
}
